# 自定义配置
com:
  huige:
    erp:
      ac:
        loginEndpoint: /login
        successEndpoint: /index
        kickoutEndpoint: /login
        urlWhiteList:
          - /css/**
          - /js/**
          - /img/**
          - /images/**
          - /json/**
          - /auth/navs
          - /lib/**
          - /swagger*/**
          - /doc.html
          - /favicon.ico
          - /auth/login