server:
  port: 9090

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: redis
    timeout: 0
  profiles:
    active: module-common,module-ac
  thymeleaf:
    cache: false
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML5
    content-type: text/html
